export const CONTRATACION_MESSAGE = {
    M09_VAL_BUSQ_CRITERIOS: 'NO SE ENCONTRÓ INFORMACIÓN PARA LOS CRITERIOS DE BÚSQUEDA INGRESADO',
    M38_VAL_COD_MODULAR: '"CÓDIGO MODULAR NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON SEIS (06) O SIETE (07) DÍGITOS"',
    M43_VAL_CRIT_BUSQUEDA: "DEBE INGRESAR POR LO MENOS UN CRITERIO DE BÚSQUEDA",
    M64_VAL_PLAZA_DIGITOS: '"CÓDIGO NO VÁLIDO, DEBE INGRESAR UN CÓDIGO DE PLAZA CON DOCE (12) DÍGITOS"',
    M08_FRM_COMPLETAR_DATOS: '"COMPLETAR LOS DATOS REQUERIDOS"',
}
