
export const SNACKBAR_BUTTON = {
    CLOSE: 'Cerrar',
    CANCEL: 'Cancelar',
    OK: 'Ok',
    ACEPTED: 'Aceptar',
    DEFAULT: 'Aceptar'
}

export const HTTP_MESSAGE = {
    DEFAULT: 'EL SERVIDOR NO RESPONDIO A LA SOLICITUD DEL USUARIO, SI PERSISTE ESTE ERROR POR FAVOR COMUNÍQUESE CON EL UGEL MAS CERCANO',
    CONTINUE: 'EL SERVIDOR SOLO HA RECIBIDO UNA PARTE DE LA SOLICITUD, PERO MIENTRAS NO HAYA SIDO RECHAZADA, UD. DEBE CONTINUAR CON LA OPERACIÓN.',
    SWITCHING_PROTOCOLS: 'EL SERVIDOR CAMBIÓ DE PROTOCOLO DE COMUNICACIÓN, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA.',
    //2×× SUCCESS
    OK: 'LA OPERACIÓN SE REALIZÓ DE MANERA SATISFACTORIA.',
    CREATED: 'LA OPERACIÓN ESTÁ COMPLETA Y SE CREÓ UNA NUEVA SOLICITUD.',
    ACCEPTED: 'LA SOLICITUD SE ACEPTA PARA SU PROCESAMIENTO, PERO EL PROCESAMIENTO NO ESTÁ COMPLETO.',
    NON_AUTHORITATIVE_INFORMATION: 'LA INFORMACIÓN EN EL ENCABEZADO DE LA ENTIDAD ES DE UNA COPIA LOCAL O DE TERCEROS, NO DEL SERVIDOR ORIGINAL.',
    NO_CONTENT: 'SE PROPORCIONA UN CÓDIGO DE ESTADO Y UN ENCABEZADO EN LA RESPUESTA, PERO NO HAY UN CUERPO DE ENTIDAD EN LA RESPUESTA.',
    RESET_CONTENT: 'EL NAVEGADOR DEBE BORRAR EL FORMULARIO UTILIZADO PARA ESTA TRANSACCIÓN PARA OBTENER INFORMACIÓN ADICIONAL.',
    PARTIAL_CONTENT: 'EL SERVIDOR ESTÁ DEVOLVIENDO DATOS PARCIALES DEL TAMAÑO SOLICITADO. SE USA EN RESPUESTA A UNA SOLICITUD QUE ESPECIFICA UN ENCABEZADO DE RANGO. EL SERVIDOR DEBE ESPECIFICAR EL RANGO INCLUIDO EN LA RESPUESTA CON EL ENCABEZADO CONTENT-RANGE.',
    //3×× REDIRECTION
    MULTIPLE_CHOICES: 'LISTA DE ENLACES. EL USUARIO PUEDE SELECCIONAR UN ENLACE E IR A ESA UBICACIÓN. MÁXIMO CINCO DIRECCIONES.',
    MOVED_PERMANENTLY: 'LA PÁGINA SOLICITADA SE HA MOVIDO A UNA NUEVA URL.',
    FOUND: 'LA PÁGINA SOLICITADA SE HA MOVIDO TEMPORALMENTE A UNA NUEVA URL.',
    SEE_OTHER: 'LA PÁGINA SOLICITADA SE PUEDE ENCONTRAR EN UNA URL DIFERENTE.',
    NOT_MODIFIED: 'ESTE ES EL CÓDIGO DE RESPUESTA A UN ENCABEZADO IF-MODIFIED-SINCE O IF-NONE-MATCH , DONDE LA URL NO SE HA MODIFICADO DESDE LA FECHA ESPECIFICADA.',
    USE_PROXY: 'SE DEBE ACCEDER A LA URL SOLICITADA A TRAVÉS DEL PROXY MENCIONADO EN EL ENCABEZADO UBICACIÓN.',
    TEMPORARY_REDIRECT: 'LA PÁGINA SOLICITADA SE HA MOVIDO TEMPORALMENTE A UNA NUEVA URL.',
    //4×× CLIENT ERROR
    BAD_REQUEST: 'EL SERVIDOR NO ENTENDIÓ LA SOLICITUD DEL USUARIO, SE HA PRODUCIDO UN ERROR INESPERADO EN UNO DE NUESTROS SERVIDORES.',
    UNAUTHORIZED: 'LA SOLICITUD REQUERIDA NECESITA AUTORIZACIÓN, UD. NO TIENE PERMISO PARA ACCEDER AL RECURSO. SERÁ REDIRIGIDO A LA PÁGINA DE INICIO DE SESIÓN.',
    PAYMENT_REQUIRED: 'AÚN NO PUEDES USAR ESTE CÓDIGO.',
    FORBIDDEN: 'ESTÁ PROHIBIDO EL ACCESO A LA PÁGINA SOLICITADA.',
    NOT_FOUND: 'EL SERVIDOR NO PUEDE ENCONTRAR EL RECURSO SOLICITADO.',
    METHOD_NOT_ALLOWED: 'EL MÉTODO ESPECIFICADO EN LA SOLICITUD NO ESTÁ PERMITIDO.',
    NOT_ACCEPTABLE: 'EL SERVIDOR SOLO PUEDE GENERAR UNA RESPUESTA QUE NO ES ACEPTADA POR EL CLIENTE.',
    PROXY_AUTHENTICATION_REQUIRED: 'DEBE AUTENTICARSE CON UN SERVIDOR PROXY ANTES DE QUE SE PUEDA ATENDER ESTA SOLICITUD.',
    REQUEST_TIMEOUT: 'LA SOLICITUD TARDÓ MÁS DE LO QUE EL SERVIDOR ESTABA PREPARADO PARA ESPERAR.',
    CONFLICT: 'LA SOLICITUD NO SE PUDO COMPLETAR DEBIDO A UN CONFLICTO.',
    GONE: 'LA PÁGINA SOLICITADA YA NO ESTÁ DISPONIBLE.',
    LENGTH_REQUIRED: 'LA "LONGITUD DEL CONTENIDO" NO ESTÁ DEFINIDA. EL SERVIDOR NO ACEPTARÁ LA SOLICITUD SIN ELLA.',
    PRECONDITION_FAILED: 'LA CONDICIÓN PREVIA DADA EN LA SOLICITUD ES EVALUADA COMO FALSA POR EL SERVIDOR.',
    PAYLOAD_TOO_LARGE: 'EL SERVIDOR NO ACEPTARÁ LA SOLICITUD PORQUE LA ENTIDAD DE LA SOLICITUD ES DEMASIADO GRANDE.',
    REQUEST_URI_TOO_LONG: 'EL SERVIDOR NO ACEPTARÁ LA SOLICITUD PORQUE LA URL ES DEMASIADO LARGA. OCURRE CUANDO CONVIERTE UNA SOLICITUD DE "PUBLICACIÓN" EN UNA SOLICITUD DE "OBTENCIÓN" CON UNA INFORMACIÓN DE CONSULTA LARGA.',
    UNSUPPORTED_MEDIA_TYPE: 'EL SERVIDOR NO ACEPTARÁ LA SOLICITUD PORQUE EL TIPO DE MEDIO NO ES COMPATIBLE.',
    REQUESTED_RANGE_NOT_SATISFIABLE: 'EL RANGO DE BYTES SOLICITADO NO ESTÁ DISPONIBLE Y ESTÁ FUERA DE LOS LÍMITES.',
    EXPECTATION_FAILED: 'ESTE SERVIDOR NO PUDO CUMPLIR LA EXPECTATIVA DADA EN UN CAMPO DE ENCABEZADO DE SOLICITUD EXPECT.',
    //5×× SERVER ERROR
    INTERNAL_SERVER_ERROR: 'LA SOLICITUD NO SE COMPLETÓ. EL SERVIDOR ENCONTRÓ UN ERROR INESPERADO.',
    NOT_IMPLEMENTED: 'LA SOLICITUD NO SE COMPLETÓ. EL SERVIDOR NO ADMITE LA FUNCIONALIDAD REQUERIDA.',
    BAD_GATEWAY: 'LA SOLICITUD NO SE COMPLETÓ. EL SERVIDOR RECIBIÓ UNA RESPUESTA NO VÁLIDA DEL SERVIDOR ASCENDENTE.',
    SERVICE_UNAVAILABLE: 'LA SOLICITUD NO SE COMPLETÓ. EL SERVIDOR SE ESTÁ SOBRECARGANDO O CAYENDO TEMPORALMENTE.',
    GATEWAY_TIMEOUT: 'SE AGOTÓ EL TIEMPO DE ESPERA DE LA PUERTA DE ENLACE.',
    HTTP_VERSION_NOT_SUPPORTED: 'EL SERVIDOR NO ADMITE LA VERSIÓN "PROTOCOLO HTTP".',
    INSUFFICIENT_STORAGE: 'LA SOLICITUD NO SE COMPLETÓ. EL SERVIDOR NO TIENE SUFICIENTE ESPACIO EN DISCO.',
    LOOP_DETECTED: 'LA SOLICITUD NO SE COMPLETÓ. EL SERVIDOR DETECTÓ BUCLE INFINITO.',
    NETWORK_AUTHENTICATION_REQUIRED: 'LA SOLICITUD NO SE COMPLETÓ. SE NECESITA AUTORIZACIÓN PARA REALIZAR ESTA OPERACIÓN.',
    NETWORK_CONNECT_TIMEOUT_ERROR: 'LA SOLICITUD NO SE COMPLETÓ. ERROR DE RED, LA CONEXIÓN DE INTERNET ES DEMASIADO LENTA PARA PROCESAR LA SOLICITUD.'
};

export const PASSPORT_MESSAGE = {
    //GENERIC MESSAGES
    END_SESION: '"SU SESIÓN HA EXPIRADO, UD. SERÁ REDIRIGIDO A LA PÁGINA DE INICIO DE SESIÓN"',
    UNAUTHORIZED: '"UD. NO SE ENCUENTRA AUTORIZADO PARA ACCEDER AL SISTEMA. SERÁ REDIRIGIDO A LA PÁGINA DE INICIO DE SESIÓN"',
    PERMISO_NOT_FOUND: '"UD. NO TIENE PERMISO PARA REALIZAR ESTA OPERACIÓN. COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA"',
    BAD_REQUEST: '"EL SERVIDOR NO ENTENDIÓ LA SOLICITUD DEL USUARIO, SE HA PRODUCIDO UN ERROR INESPERADO EN UNO DE NUESTROS SERVIDORES."',
    BAD_TOKEN: '"EL SERVIDOR NO RETORÓ LA AUTORIZACIÓN PARA ACCEDER A LOS SERVICIOS DEL SERVIDOR PÚBLICO, SERÁ REDIRIGIDO AL PANEL DE SISTEMAS. GRACIAS."',
    NOT_FOUND: '"ERROR, UDS. NO SE ENCUENTRA REGISTRADO EN EL SISTEMA. COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BUTTON_UNAUTHORIZED: '"UD. NO TIENE PERMISO PARA REALIZAR ESTA OPERACIÓN. SERÁ REDIRIGIDO A LA PÁGINA DE INICIO DE SESIÓN."',
    METHOD_UNAUTHORIZED: '"UD. NO SE ENCUENTRA AUTORIZADO PARA ACCEDER A UNO O MAS OPERACIONES. SERÁ REDIRIGIDO A LA PÁGINA DE INICIO DE SESIÓN."',
    NOT_ALLOWED: '"EL SISTEMA NO PUDO ACCEDER A LOS SERVIDORES DE AUTORIZACIÓN. SERÁ REDIRIGIDO A LA PÁGINA DE INICIO DE SESIÓN."',
    OPERATION_NOT_FOUND: '"UD. NO TIENE OPERACIONES Y PERMISOS DE PASSPORT ASIGNADOS, SERA REDIRIGIDO A LA PÁGINA DE INICIO DE SESIÓN."',
    END_SESSION: '"UD. ESTÁ CERRANDO LA SESIÓN DEL USUARIO, SERÁ REDIRIGIDO A LA PÁGINA DE INICIO DE SESIÓN. GRACIAS."',
    SESION_END: '"SU SESIÓN HA CADUCADO. SERÁ REDIRIGIDO A LA PÁGINA DE INICIO DE SESIÓN."',
    CREDENTIALS_UNAUTHORIZED: '"NO PUDO OBTENER CREDENCIALES DE ACCESO, UD. SERÁ REDIRIGIDO A LA PÁGINA DE INICIO DE SESIÓN."',
    // API MESSAGES
    BUSCAR_SISTEMA_PERMISO_USUARIO: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO PASSPORT "PERMISOS DE USUARIO AL SISTEMA". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BUSCAR_SESION: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO PASSPORT "SESIONES DEL USUARIO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BUSCAR_USUARIO: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO PASSPORT "INFORMACION DEL USUARIO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BUSCAR_MENU: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO PASSPORT "MENU". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BUSCAR_ROL_USUARIO: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO PASSPORT "ROLES DEL USUARIO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BUSCAR_ACCION: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO PASSPORT "ACCIONES". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BUSCAR_AUTHORIZACION: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO PASSPORT "PERMISOS". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BOOT: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO PASSPORT "BOOT". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."'
}

export const PERSONA_MESSAGE = {
    BUSCAR_DOCUMENTO: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER VÍNCULO LABORAL" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_PERSONA: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER PERSONA" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_DISCAPACIDADES: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER DISCAPACIDADES" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_DISCAPACIDAD: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER DISCAPACIDAD" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_FAMILIARES: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER FAMILIARES" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_FAMILIAR: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER FAMILIAR" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_FORMACIONES_ACADEMICAS: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER FORMACIONES ACADÉMICAS" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_FORMACION_ACADEMICA: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER FORMACIÓN ACADÉMICA" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_CAPACITACIONES: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER CAPACITACIONES" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_CAPACITACION: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER CAPACITACIÓN" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_PRODUCCIONES_INTELECTUALES: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER PRODUCCIONES INTELECTUALES" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_PRODUCCION_INTELECTUAL: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER PRODUCCIÓN INTELECTUAL" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_IDIOMAS: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER IDIOMAS" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_EXPERIENCIAS_PROFESIONALES: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER EXPERIENCIAS PROFESIONALES" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.',
    BUSCAR_EXPERIENCIA_PROFESIONAL: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER EXPERIENCIA PROFESIONAL" DEL SERIVIDOR PÚBLICO. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL UGEL MAS CERCANO.'
}

export const DOCUMENTO_MESSAGE = {
    CREAR: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO DE DOCUMENTOS "CREAR NUEVO DOCUMENTO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA.',
    DESCARGAR: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO DE DOCUMENTOS "DESCARGAR DOCUMENTO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA.',
    IMAGE_PREVIEW: 'ERROR, NO SE PUDO ACCEDER AL SERVICIO DE DOCUMENTOS "BUSCAR IMAGEN" DEL PERSONAL. SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA.'
}

export const KONG_MESSAGE = {
    AUTHORIZE: 'UD. NO CUENTA CON CÓDIGO DE AUTORIZACIÓN PARA ACCEDER.',
    TOKEN: 'EL CÓDIGO DE AUTORIZACIÓN ES INCORRECTO, IMPOSIBLE OBTENER LOS DATOS DE AUTORIZACIÓN.',
    REFRESH_TOKEN: 'NO SE PUDO OBTENER LOS DATOS DE ACCESO.'
}

export const ACCIONES_GRABADAS_MESSAGE = {
    EXPORTAR: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "EXPORTAR ACCION GRABADA A EXCEL". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CONSULTAR: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CONSULTAR ACCION GRABADA". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    ELIMINAR: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "ELIMINAR ACCION GRABADA". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_TIPOS_RESOLUCION: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR TIPOS DE RESOLUCIÓN". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_TIPOS_DOCUMENTO_IDENTIDAD: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR TIPOS DE DOCUMENTO DE IDENTIDAD". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_TIPOS_DOCUMENTO_SUSTENTO: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR TIPOS DE DOCUMENTO DE SUSTENTO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_TIPOS_FORMATO_SUSTENTO: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR TIPOS DE FORMATO DE SUSTENTO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_GENEROS_PERSONA: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR GENEROS DE LA PERSONA". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_TIPOS_CENTRO_TRABAJO: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR TIPOS DE CENTRO DE TRABAJO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_SERVIDORES_PUBLICOS: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CONSULTAR SERVIDORES PÚBLICOS". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BUSCAR_SERVIDOR_PUBLICO: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "BUSCAR SERVIDOR PÚBLICO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    OBTENER_SERVIDOR_PUBLICO: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "OBTENER SERVIDOR PÚBLICO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_CENTROS_TRABAJO: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CONSULTAR CENTROS DE TRABAJO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BUSCAR_CENTRO_TRABAJO: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "BUSCAR CENTRO DE TRABAJO". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_PLAZAS: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CONSULTAR PLAZAS". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    BUSCAR_PLAZA: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "BUSCAR PLAZA". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_REGIMENES_LABORALES: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR REGÍMENES LABORALES". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_GRUPOS_ACCION: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR GRUPOS DE ACCIÓN". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_ACCIONES: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR ACCIONES". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_MOTIVOS_ACCION: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR MOTIVOS DE ACCIÓN". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_ANIOS_APERTURADOS: '"ERROR, NO SE PUDO ACCEDER AL SERVICIOS "CARGAR AÑOS APERTURADOS". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_ESTADOS_ACCIONES_GRABADAS: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CONSULTAR ESTADOS DE ACCIONES GRABADAS". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    CARGAR_CODIGO_TIPO_SEDE: '"ERROR, NO SE PUDO ACCEDER AL SERVICIO "CARGAR TIPOS DE RESOLUCION". SI PERSISTE EL ERROR, COMUNÍQUESE CON EL ADMINISTRADOR DEL SISTEMA."',
    GENERAR_PROYECTO_RESOLUCION: '"Ocurrió un error al generar el Proyecto de Resolución. Vuelva a intentar la operación."',
    M09: '"NO SE ENCONTRÓ INFORMACIÓN PARA LOS CRITERIOS DE BÚSQUEDA INGRESADOS"',
    M29:'¿ESTÁ SEGURO QUE DESEA GENERAR EL PROYECTO DE RESOLUCIÓN?',
    M34: '"NÚMERO DE DOCUMENTO NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON OCHO (8) DÍGITOS"',
    M38: '"CÓDIGO MODULAR NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON SESI(6) O SIETE (7) DÍGITOS"',
    M64: '"CÓDIGO NO VÁLIDO, DEBE INGRESAR UN CÓDIGO DE PLAZA CON DOCE (12) DÍGITOS"',
    M73: '"NO SE PUEDE EXPORTAR, YA QUE NO EXISTE INFORMACIÓN EN LA GRILLA"',
    M91: '"DEBE SELECCIONAR COMO MÍNIMO UN REGISTRO DE LA GRILLA"',
    M116: '"NÚMERO DE DOCUMENTO NO VÁLIDO, DEBE INGRESAR UN NÚMERO ENTRE NUEVE(9) Y DOCE (12) DÍGITOS"',
    M124:'“DEBE REGISTRAR COMO MÍNIMO UN DOCUMENTO DE SUSTENTO QUE SE MUESTRE EN EL VISTO DEL PROYECTO”'
};
export const PROYECTO_RESOLUCION_MESSAGE = {
    M01: '"NÚMERO DE PROYECTO DE RESOLUCIÓN NO VÁLIDO, DEBE INGRESAR UN NÚMERO DE SEIS(6) DÍGITOS"',
    M09: '"NO SE ENCONTRÓ INFORMACIÓN PARA LOS CRITERIOS DE BÚSQUEDA INGRESADOS"',
    M29:'¿ESTÁ SEGURO QUE DESEA GENERAR EL PROYECTO DE RESOLUCIÓN?',
    M34: '"NÚMERO DE DOCUMENTO NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON OCHO (8) DÍGITOS"',
    M38: '"CÓDIGO MODULAR NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON SESI(6) O SIETE (7) DÍGITOS"',
    M64: '"CÓDIGO NO VÁLIDO, DEBE INGRESAR UN CÓDIGO DE PLAZA CON DOCE (12) DÍGITOS"',
    M73: '"NO SE PUEDE EXPORTAR, YA QUE NO EXISTE INFORMACIÓN EN LA GRILLA"',
    M91: '"DEBE SELECCIONAR COMO MÍNIMO UN REGISTRO DE LA GRILLA"',
    M116: '"NÚMERO DE DOCUMENTO NO VÁLIDO, DEBE INGRESAR UN NÚMERO ENTRE NUEVE(9) Y DOCE (12) DÍGITOS"',
    M124:'“DEBE REGISTRAR COMO MÍNIMO UN DOCUMENTO DE SUSTENTO QUE SE MUESTRE EN EL VISTO DEL PROYECTO”'    
};