export enum TablaMetodosAprobados {
    //metodos page principal
   GET_ROLES = 1,
   GET_CONSULTAR_GRID = 3, 
   EXPORTAR = 4,   
   RECHAZAR_ADECUACION = 5,
   RECHAZAR_REUBICACION = 6
}

export enum TablaFuncionalidad {
    REUBICACION_POR_RACIONALIZACION = 1,
    REUBICACION_REASIGNACION_POR_RACIONALIZACION = 2,
    ADECUACION_POR_RACIONALIZACION = 3,
    REUBICACION_PLAZA_EVENTUAL = 4,
    REUBICACION_CUADRO_HORAS = 5,
    REUBICACION_REASIGNACION_CUADRO_HORAS = 6
}

