export enum TablaEstadoAdecuacion {
    EN_PROCESO = 1,
    EN_VALIDACION = 2,
    VALIDADO = 3,
    EN_PROYECTO = 4,
    APROBADO = 5,
    RECHAZADO = 6
}

export enum TablaTipoCentroTrabajoAdecuacion {
    SEDE_MINEDU = 1,
    SEDE_ADMINISTRATIVA_DRE = 2,
    INSTITUCION_EDUCATIVA_DRE = 3,
    INSTITUTO_SUPERIOR_DRE = 4,
    SEDE_ADMINISTRATIVA_UGEL = 5,
    INSTITUCION_EDUCATIVA_UGEL = 6,
    INSTITUTO_SUPERIOR_UGEL = 7
}

export enum TablaAdecuacionNivelInstancia {
    MINEDU = 1,
    DRE = 2,
    UGEL = 3
}

export enum TablaMetodosAdecuacion {
    //metodos page principal
    GET_ROLES = 1,
    GET_CENTROS_TRABAJO = 2,
    GET_INSTANCIAS = 3,
    GET_SUB_INSTANCIAS = 4,
    GET_REGIMENES_LABORALES = 5,
    GET_AREAS_DESEMPENIO_LABORAL = 6,
    GET_TIPOS_CARGO = 7,
    GET_CARGOS = 8,
    GET_UNIDAD_ORGANIZACIONAL_1 = 9,
    GET_UNIDAD_ORGANIZACIONAL_2 = 10,
    GET_UNIDAD_ORGANIZACIONAL_3 = 11,
    GET_BUSCAR_CENTRO_TRABAJO = 12,
    GET_CONSULTAR_GRID = 13,
    CREAR = 14,
    EDITAR = 15,
    VER = 16,
    EXPORTAR = 17,
    PROYECTAR = 18,
    //metodos page adecuar
    GET_CATEGORIAS_REMUNERATIVAS = 19,
    GET_JORNADAS_LABORALES = 20,
    GET_MOTIVOS_ACCION = 21,
    GET_CONSULTAR_PLAZA = 22,
    GET_INFORMACION_PLAZA = 23,
    GET_TIPO_DOCUMENTO_SUSTENTO = 24,
    GET_CONSULTAR_DOCUMENTO_SUSTENTO = 25,
    GET_CONSULTAR_PLAZA_ADECUADA = 26,
    GET_DESCARGAR_DOCUMENTO = 27,
    GENERAR_PROYECTO_RESOLUCION = 28,
    GET_TIPO_CENTRO_TRABAJO = 29,
    CONSULTAR_CENTRO_TRABAJO = 30,
    ACCIONES_GRABADAS = 31,
    CREAR_SOLICITAR = 32,
    APROBAR = 33,
    RECHAZAR = 34,

}