export enum CodigoNivelAcademicoEnum {
    PRIMARIA = 1,
    SECUNDARIA = 2,
    SUPERIOR = 6,
    SUPERIOR_POSTGRADO = 10,
    TECNICO_PRODUCTIVA = 11
}
export enum CatalogoItemEnum {
    TIPOS_DOCUMENTOS_IDENTIDAD = 6,
    TIPOS_ESTADO_PRONOEI = 201,
    NIVEL_EDUCATIVO = 174,
    SITUACION_ACADEMICA = 60,
    TIPO_ZONA = 38
}

export enum TipoDocumentosIdentidadActivoEnum {
    DNI = 1,
    PASAPORTE = 4,
    CARNET_EXTRANJERIA = 5
}

export enum RegimenGrupoAccionEnum {
    PRONOEI = 649
}

export enum TipoEstadoPronoeiEnum {
    REGISTRADO = 1,
    ELIMINADO = 2,
    PENDIENTE_PROYECTO = 3,
    CON_PROYECTO = 4,
    CON_RESOLUCION = 5
}

export enum TipoZonaEnum {
    URBANA = 1,
    RURAL = 2
}

export enum SituacionResolucionEnum {
    MODIFICADO = 1,
    RECTIFICADO = 2,
    DEJAR_SIN_EFECTO = 3,
    DECLARADO_NULO = 4,
    DAR_POR_CONCLUIDO = 5,
    ORIGINAL = 6
}

export enum TipoResolucionEnum {
    NO_ESPECIFICADO = 8
}

export enum NivelInstanciaCodigoEnum {
    MINEDU = 1,
    DRE = 2,
    UGEL = 3,
}

export enum TablaUsuarioRol {
    ResponsablePersonal = 1,
    EspecialistaDITEN = 2,
    EspecialistaUPP = 3,
    EspecialistaAIRHSP = 4,
    ResponsablePresupuesto = 5
}

export enum TipoCentroTrabajoCodigoEnum {
    Minedu = 1,
    SedeAdministrativaDRE = 2,
    InstitucionEducativaDRE = 3,
    InstitutoSuperiorDRE = 4,
    SedeAdministrativaUGEL = 5,
    InstitucionEducativaUgel = 6,
    InstitutoSuperiorUgel = 7,
    SedeCentroLaboralDre = 8,
    SedeCentroLaboralUgel = 9,
}


export const MESSAGE_GESTION = {

    EX_FILTER_NOTFOUND: "NO SE ENCONTRÓ INFORMACIÓN PARA LOS CRITERIOS DE BÚSQUEDA INGRESADOS",
    EX03: 'NÚMERO DE DOCUMENTO NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON OCHO (8) DÍGITOS',
    EX05: 'CÓDIGO MODULAR NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON SEIS (06) O SIETE (07) DÍGITOS',
    EX08: 'NÚMERO DE DOCUMENTO NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON NUEVE (9) A DOCE (12) CARACTERES',
    M01: 'DEBE INGRESAR POR LO MENOS UN CRITERIO DE BÚSQUEDA',
    M02: '¿ESTÁ SEGURO QUE DESEA GUARDAR LA INFORMACIÓN?',
    M03: '¿ESTÁ SEGURO QUE DESEA GUARDAR LOS CAMBIOS?',
    M05: '¿ESTÁ SEGURO QUE DESEA ELIMINAR LA INFORMACIÓN?',
    M07: 'OPERACIÓN REALIZADA DE FORMA EXITOSA',
    M08: 'COMPLETAR LOS DATOS REQUERIDOS',
    M29: '¿ESTÁ SEGURO QUE DESEA GENERAR EL PROYECTO DE RESOLUCIÓN?',
    M38: 'CÓDIGO MODULAR NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON SEIS (06) O SIETE (7) DÍGITOS',
    M47: 'SERVIDOR PÚBLICO NO ENCONTRADO',
    M43: 'DEBE INGRESAR LA INFORMACIÓN PARA REALIZAR LA BÚSQUEDA',
    M63: 'FECHA NO VÁLIDA, FECHA DEBE SER MAYOR O IGUAL A LA FECHA ACTUAL',
    M66: 'FECHA NO VÁLIDA, VUELVA A INGRESAR',
    M88: 'FECHA NO VÁLIDA, DEBE INGRESAR UNA FECHA MAYOR A LA FECHA DE INICIO',

    M90: '¿ESTÁ SEGURO QUE DESEA ENVIAR LA INFORMACIÓN A ACCIONES GRABADAS?',
    M91: 'DEBE SELECCIONAR COMO MÍNIMO UN REGISTRO DE LA GRILLA',
    M124: 'DEBE REGISTRAR COMO MÍNIMO UN DOCUMENTO DE SUSTENTO QUE SE MUESTRE EN EL VISTO DEL PROYECTO',
    M135: 'EL NÚMERO DE DOCUMENTO YA SE ENCUENTRA REGISTRADO, DEBE INGRESAR OTRO NÚMERO ',

    INVALID_TIPO_DOCUMENTO_PERSONA: 'SELECCIONE EL TIPO DE DOCUMENTO DE IDENTIDAD DE LA PERSONA',
    INVALID_NRO_DOCUMENTO_PERSONA: 'INGRESE EL NÚMERO DE DOCUMENTO DE IDENTIDAD DE LA PERSONA PARA REALIZAR LA BÚSQUEDA',
    INVALID_CANTIDAD_DIAS: 'LA CANTIDAD DE DÍAS DEBE SER MAYOR O IGUAL A LA DURACIÓN MÍNIMA NACIONAL Y MENOR O IGUAL A LA DURACIÓN MÁXIMA NACIONAL',
    INVALID_FOLIOS: 'INGRESE UN NÚMERO DE FOLIOS VÁLIDO',
}
