export const MESSAGE_GESTION = {

    EX_FILTER_NOTFOUND: "NO SE ENCONTRÓ INFORMACIÓN PARA LOS CRITERIOS DE BÚSQUEDA INGRESADOS",
    EX03: 'NÚMERO DE DOCUMENTO NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON OCHO (8) DÍGITOS',
    EX08: 'NÚMERO DE DOCUMENTO NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON NUEVE (9) A DOCE (12) CARACTERES',
    M01: 'DEBE INGRESAR POR LO MENOS UN CRITERIO DE BÚSQUEDA'
}
