export enum TipoDocumentoIdentidadEnum {
    DNI = 1,
    CARNET_EXTRANJERIA = 2,
    PASAPORTE = 3
}


export enum ResultadoFinalizarEtapaEnum {
    EXISTE_ADJ_CONRESOL = 999,
    NO_EXISTE_DATA_CAL = 998

}
export enum ResultadoEliminarCagaEnum {
    NO_EXISTE_APTOS_ADJ = 999,
    NO_EXISTE_DATA_CAL = 998

}
export enum ResultadoOperacionEnum {
    NotFound = 404,
    UnprocessableEntity = 422,
    InternalServerError
}
export enum EstadoAscensoEnum {
    EN_PROCESO = 1,
    ELIMINADO = 2,
    CANCELADO = 3,
    DESIERTO = 4,
    FINALIZADO = 5
}
export enum EstadoEtapaEnum {
    EN_PROCESO = 1,
    DESIERTO = 2,
    CANCELADO = 3,
    ELIMINADO = 4,
    FINALIZADO = 5,
}
export enum EstadoDesplazamientoEnum {
    REGISTRADO = 1,
    ELIMINADO = 2,
    PENDIENTE_PROYECTO = 3,
    CON_PROYECTO = 4,
    CON_RESOLUCION = 5,
    OBSERVADO = 6,
    PENDIENTE_AUTORIZACION = 7,
    AUTORIZADO = 8,
    NO_AUTORIZADO = 9
}
export enum EstadoCalificacionEnum {
    EN_PROCESO = 1,
    ELIMINADO = 2,
    CANCELADO = 3,
    DESIERTO = 4,
    FINALIZADO = 5
}

export enum EstadoAdjudicacionEnum {
    APTO = 1,
    ADJUDICADO = 2,
    NO_ADJUDICADO = 3,
    OBSERVADO = 4,
    CON_RESOLUCION = 5
}
export enum TablaConfiguracionFormatoCarga {
    EBR = 7,
    ETP = 8
};

export const PAGE_ORIGEN = {
    MENSUAL: 2,
    SERVIDOR: 3,
};

export const ModalidadEdicativaEnum = {
    EBR: "EBR",
    ETP: "ETP",
};

export const accionPersonalRegistro = {
    REGISTRADO: "REGISTRADO",
    ELIMINADO: "ELIMINADO",
    PENDIENTEDEPROYECTO: "PENDIENTE DE PROYECTO",
    CONPROYECTO: "CON PROYECTO",
    CONRESOLUCION: "CON RESOLUCION",
    OBSERVADO: "OBSERVADO",
    PENDIENTEDEAUTORIZACION: "PENDIENTE DE AUTORIZACION",
    AUTORIZADO: "AUTORIZADO",
    NOAUTORIZADO: "NO AUTORIZADO"
}

export const accionReference = {
    DESTAQUE: 12,
    ENCARGATURA: 13,
    PERMUTA: 14,
    ROTACION: 16,
    UBICACION: 17,
    DESIGNACION: 11,
    REASIGNACION: 15,
    ASCENSOCARGO: 10,
    ASCENSOESCALAMAGISTERIAL: 3,
    UBICACIONESCALAMAGISTERIAL: 5,
    RETORNAR: 73
}
export const accionCodeReference = {
    DESTAQUE: 14,
    ENCARGATURA: 15,
    PERMUTA: 16,
    ROTACION: 18,
    UBICACION: 19,
    DESIGNACION: 13,
    REASIGNACION: 17,
    // ASCENSOCARGO: 10,
    ASCENSOESCALAMAGISTERIAL: 5,
    RETORNAR: 73
}

export const codigosSituacionLaboralEnum = {
    EN_ACTIVIDAD: 1,
    DESTACADO: 2,
    REASIGNADO: 3,
    ENCARGADO: 4,
    DESIGNADO: 5,
    CESADO: 6,
    EN_ABANDONO_CARGO: 7,
    CON_SANCION: 8,
    CON_LICENCIA_CON_GOCE: 9,
    CON_LICENCIA_SIN_GOCE: 10,
    MEDIDA_PREVENTIVA: 11,
    SIN_ACTIVIDAD: 12
}

export const regimenLaboral = {
    LEY_29944: 1,
    LEY_30512: 2,
    LEY_276: 5,
    LEY_30493: 4,
    LEY_30328: 3
}

export const motivoAccion = {
    ASCENSO_CARGO: 18,
    DE_FUNCIONES: 28,
    DE_PUESTO: 29,
    CONCURSO_PUBLICO: 20,
    INTERES_PERSONAL: 32,
    POR_RATIFICACION: 23,
    RAZONES_SALUD: 26,
    UNIDAD_FAMILIAR: 27
}

export const grupoAccion = {
    DESPLAZAMIENTO: 5
}

export const cargarCombos = {
    IDROLPASSPORT: 2,
    IDNIVELINSTANCIA: 8
}

export const tipoSede = {
    DRE: 1,
    UGEL: 2
}

export const codigoAreaDesempenioLaboral = {
    ADMINISTRATIVO: 1,
    AUXILIAR_EDUCACION: 2,
    FORMACION_DOCENTE: 3,
    GESTION_INSTITUCIONAL: 4,
    GESTION_PEDAGOGICA: 5,
    INNOVACION_INVESTIGACION: 6,
    PROFESIONAL_SALUD: 7,
    SIN_AREA_DESEMPEÑO: 8,
    NO_ESPECIFICADO: 9,
    DOCENCIA: 10
}

export enum TablaEquivalenciaSede {
    codigoTipoSedeOficina = "TS005",
    codigoTipoSedeDre = "TS001",
    codigoTipoSedeUgel = "TS002",
    // codigoTipoSedeSinSede = "TS012",
    codigoTipoSedeSinSede = "TS013",
    codigoTipoSede = "TS005",
    codigoSede = "000000"
}


export const MESSAGE_GESTION = {

    EX03: '"NÚMERO DE DOCUMENTO NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON OCHO (8) DÍGITOS"',
    EX05: '"CODIGO MODULAR NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON SIETE (7) DÍGITOS"',
    EX08: 'NÚMERO DE DOCUMENTO NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON NUEVE (9) A DOCE (12) CARACTERES',

    M01: '"DEBE INGRESAR POR LO MENOS UN CRITERIO DE BÚSQUEDA"',
    M02: '¿ESTÁ SEGURO QUE DESEA GUARDAR LA INFORMACION?',
    M03: '¿ESTÁ SEGURO QUE DESEA GUARDAR LOS CAMBIOS?',
    M05: '¿ESTÁ SEGURO QUE DESEA ELIMINAR LA INFORMACION?',
    M07: '"OPERACION REALIZADA DE FORMA EXITOSA"',
    M08: '"COMPLETAR LOS DATOS REQUERIDOS"',
    M29: '¿ESTÁ SEGURO QUE DESEA GENERAR EL PROYECTO DE RESOLUCION?',
    M38: '"CODIGO MODULAR NO VÁLIDO, DEBE INGRESAR UN NÚMERO CON SEIS (06) O SIETE (7) DÍGITOS"',
    M47: 'SERVIDOR PÚBLICO NO ENCONTRADO',
    M43: '"DEBE INGRESAR LA INFORMACION PARA REALIZAR LA BÚSQUEDA"',
    M63: '"FECHA NO VÁLIDA, FECHA DEBE SER MAYOR O IGUAL A LA FECHA ACTUAL"',
    M66: 'FECHA NO VÁLIDA, VUELVA A INGRESAR',
    M88: '"FECHA NO VÁLIDA, DEBE INGRESAR UNA FECHA MAYOR A LA FECHA DE INICIO"',

    M90: '¿ESTÁ SEGURO QUE DESEA ENVIAR LA INFORMACION A ACCIONES GRABADAS?',
    M91: '"DEBE SELECCIONAR COMO MÍNIMO UN REGISTRO DE LA GRILLA"',
    M124: '"DEBE REGISTRAR COMO MÍNIMO UN DOCUMENTO DE SUSTENTO QUE SE MUESTRE EN EL VISTO DEL PROYECTO"',

    INVALID_TIPO_DOCUMENTO_PERSONA: '"SELECCIONE EL TIPO DE DOCUMENTO DE IDENTIDAD DE LA PERSONA"',
    INVALID_NRO_DOCUMENTO_PERSONA: '"INGRESE EL NÚMERO DE DOCUMENTO DE IDENTIDAD DE LA PERSONA PARA REALIZAR LA BÚSQUEDA"',
    INVALID_CANTIDAD_DIAS: '"LA CANTIDAD DE DÍAS DEBE SER MAYOR O IGUAL A LA DURACION MÍNIMA NACIONAL Y MENOR O IGUAL A LA DURACION MÁXIMA NACIONAL"',
    INVALID_FOLIOS: '"INGRESE UN NÚMERO DE FOLIOS VÁLIDO"',
}


export enum TipoDocumentosIdentidadActivoEnum {
    DNI = 1,
    PASAPORTE = 4,
    CARNET_EXTRANJERIA = 5
}