export const DEFAULT_MESSAGES = {
    CONFIRM_GUARDA_REGISTRO: (msg) => `¿ESTÁ SEGURO DE ${msg} EL REGISTRO?`,
    GUARDA_REGISTRO_SUCCESS: '"SE GUARDO LA INFORMACIÓN DE MANERA CORRECTA."',
    OPERACION_SUCCESS: '"OPERACIÓN REALIZADA DE FORMA EXITOSA"',
    CONFIRM_GUARDAR_INFORMACION:
        "¿ESTÁ SEGURO QUE DESEA GUARDAR LA INFORMACIÓN?",
    OPERACION_ERROR: '"LA OPERACIÓN REALIZADA PRESENTÓ UN ERROR."',
    DATOS_REQUERIDOS_NO_FORMATO_CORRECTO:
        '"LOS DATOS INGRESADOS NO TIENEN EL FORMATO CORRECTO."',
    CONFIRMAR_CERRAR_DATOS_PENDIENTE:
        "¿ESTÁ SEGURO QUE DESEA CERRAR?. TIENE CAMBIOS PENDIENTES SIN GUARDAR",
};
